CoachAssisant/Models/WorkoutExercise.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace CoachAssisant.Models
{
    public class WorkoutExercise
    {


        [Required]
        public int Id { get; set; }
        
        public Exercise Exercise { get; set; }

        [Display(Name = nameof(Resources.DisplayNames.Exercise),
            ResourceType = typeof(Resources.DisplayNames))]
        [Required]
        public int ExerciseId { get; set; }

        public Workout Workout { get; set; }
        
        [Display(Name = nameof(Resources.DisplayNames.Workout),
            ResourceType = typeof(Resources.DisplayNames))]
        [Required]
        public int WorkoutId { get; set; }

        [Display(Name = nameof(Resources.DisplayNames.AlternativeName),
            ResourceType = typeof(Resources.DisplayNames))]
        public string AdditionalName { get; set; }

        [Display(Name = nameof(Resources.DisplayNames.Wraps),
            ResourceType = typeof(Resources.DisplayNames))]
        public int? Wraps { get; set; }

        [Display(Name = nameof(Resources.DisplayNames.WorkingWeight),
            ResourceType = typeof(Resources.DisplayNames))]
        public double? WorkingWeight { get; set; }

        [Display(Name = nameof(Resources.DisplayNames.NumberOfSets),
            ResourceType = typeof(Resources.DisplayNames))]
        public int? NumberOfSets { get; set; }


    }
}

CoachAssisant/Controllers/WorkoutExercisesController.cs
using CoachAssisant.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using CoachAssisant.ViewModels;
using CoachAssisant.Dtos;

namespace CoachAssisant.Controllers
{
    public class WorkoutExercisesController : Controller
    {

        private ApplicationDbContext _context;
        public WorkoutExercisesController()
        {
            _context = new ApplicationDbContext();
        }
        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        public ActionResult New(int? workoutId, int? clientId)
        {
            /*
             * change so that we check the argument passed here
             * 
             * **/            
            var exerciseTypes = _context.Exercises.ToList();

            if (workoutId.HasValue)
            {
                var workoutExercise = new WorkoutExercise();
                Workout workout = _context.Workouts.SingleOrDefault(w => w.Id == workoutId.Value);
                workoutExercise.WorkoutId = workoutId.Value;
                var viewModel = new WorkoutExerciseFormViewModel
                {
                    Exercises = exerciseTypes,
                    WorkoutExercise = workoutExercise,
                    WorkoutId = workoutId.Value
                };
                return View("WorkoutExerciseForm", viewModel);
            }                
            else if (clientId.HasValue)
            {
                return View("New");

            }                        
            else
            {
                return new HttpNotFoundResult();
            }
                                                

            
        }
        

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save(WorkoutExercise workoutExercise)
        {
            if (!ModelState.IsValid){
                var viewModel = new WorkoutExerciseFormViewModel
                {
                    WorkoutExercise = workoutExercise,
                    Exercises = _context.Exercises.ToList()
                };
                return View("WorkoutExerciseForm", viewModel);



            }
            if (workoutExercise.Id == 0)
            {
                _context.WorkoutExercises.Add(workoutExercise);
            }
            else
            {
                var workoutExerciseInDb = _context.WorkoutExercises.Single(e => e.Id == workoutExercise.Id);
                workoutExerciseInDb.ExerciseId = workoutExercise.ExerciseId;
                workoutExerciseInDb.WorkoutId = workoutExercise.WorkoutId;
                workoutExerciseInDb.Wraps = workoutExercise.Wraps;
                workoutExerciseInDb.NumberOfSets = workoutExercise.NumberOfSets;
                workoutExercise.WorkingWeight = workoutExercise.WorkingWeight;
                workoutExerciseInDb.AdditionalName = workoutExercise.AdditionalName;
            }
            _context.SaveChanges();
            // TODO: change to specific workout
            return RedirectToAction("Details", new { controller = "Workouts",
                action = "Details", Id = workoutExercise.WorkoutId });
        }

        public ActionResult Edit(int id)
        {
            var workoutExercise = _context.WorkoutExercises.SingleOrDefault(e => e.Id == id);            
            if (workoutExercise == null)
            {
                return HttpNotFound();
            }
            var viewModel = new WorkoutExerciseFormViewModel
            {                
                Exercises = _context.Exercises.ToList(),
                WorkoutExercise = workoutExercise
            };

            return View("WorkoutExerciseForm", viewModel);
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var workoutExercise = _context.WorkoutExercises.SingleOrDefault(e => e.Id == id);
            if (workoutExercise == null)
            {
                return HttpNotFound();
            }
            return View(workoutExercise);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            var workoutExercise = _context.WorkoutExercises.SingleOrDefault(e => e.Id == id);
            if (workoutExercise == null)
            {
                return HttpNotFound();
            }
            _context.WorkoutExercises.Remove(workoutExercise);
            _context.SaveChanges();
            return RedirectToAction("Details", new { controller = "Workouts",
                action = "Details", Id = workoutExercise.WorkoutId });

        }
        


    }
}

CoachAssisant/Views/WorkoutExercises/New.cshtml
@{
    ViewBag.Title = "New";
    ViewBag.HeaderClass = "header2";
    ViewBag.IsIndex = false;
    ViewBag.LinkClass = "";
}

<div class="container" style="margin-top:50px">

    <h3 style="color:#fd7364; margin-bottom:50px">Добавить упражнения</h3>    


    <form>
        <div class="form-group">
            <label>Клиент</label>
            <div class="tt-container">
                <input id="client" name="client" type="text" value="" class="form-control" />
            </div>
        </div>

        <div class="form-group">
            <label>Упражнение</label>
            <input id="exercise" name ="exercise" type="text" value="" class="form-control" />
        </div>
        <button class="btn btn-primary">Добавить</button>
    </form>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {

            var vm = {};

            var clients = new Bloodhound({
                datumTokenizer: Bloodhound.tokenizers.obj.whitespace('fullName'),
                queryTokenizer: Bloodhound.tokenizers.whitespace,                
                remote: {
                    url: '/api/clients?query=%QUERY',
                    wildcard: '%QUERY'
                }
            });

            $('#client').typeahead({                
                highlight: true
            },{
                name: 'clients',
                display: 'fullName',
                source: clients
                }).on("typeahead:select", function (e, client) {
                    vm.customerId = client.id;
                });
            var exercises = new Bloodhound({
                datumTokenizer: Bloodhound.tokenizers.obj.whitespace('name'),
                queryTokenizer: Bloodhound.tokenizers.whitespace,
                remote: {
                    url: '/api/exercises?query=%QUERY',
                    wildcard: '%QUERY'
                }
            });

            $('#exercise').typeahead({
                minLength: 3,
                highlight: true
            }, {
                    name: 'exercises',
                    display: 'name',
                    source: exercises
                }).on("typehead:select", function (e, exercise) {
                });
        })
    </script>
    }

CoachAssisant/Views/WorkoutExercises/WorkoutExerciseForm.cshtml
@model CoachAssisant.ViewModels.WorkoutExerciseFormViewModel
@{
    ViewBag.Title = "Упражнение";    
    ViewBag.HeaderClass = "header2";
    ViewBag.IsIndex = false;
    ViewBag.LinkClass = "";    
}

<div class="container" style="margin-top:50px">   
    
    <h3 style="color:#fd7364; margin-bottom:50px">@Model.Title</h3>
    @if (Model.WorkoutExercise.Id != 0)
    {
        <div id="deletebutton">
            @using (Html.BeginForm("Delete", "WorkoutExercises", new { Id = Model.WorkoutExercise.Id }))
            {
                @Html.HiddenFor(w => w.WorkoutExercise.Id)
                @Html.AntiForgeryToken()
                <button type="submit" value="Delete" class="btn btn-primary"><span class="glyphicon glyphicon-trash glyphicon-button"></span>Delete</button>
            }
        </div>
    }
    <br />
    @using (Html.BeginForm("Save", "WorkoutExercises"))
    {
        @Html.ValidationSummary(true, "Пожалуйста, исправьте некорректно заполненные поля")
        <div class="form-group">
            @Html.LabelFor(e => e.WorkoutExercise.ExerciseId)            
            @Html.DropDownListFor(e => e.WorkoutExercise.ExerciseId, new SelectList(Model.Exercises, "Id", "Name"), "Выберите упражнение",
           new { @class = "form-control"})
            @Html.ValidationMessageFor(e => e.WorkoutExercise.ExerciseId)
        </div>

        <div class="form-group">
            @Html.LabelFor(e => e.WorkoutExercise.AdditionalName)
            @Html.TextBoxFor(e => e.WorkoutExercise.AdditionalName, new { @class = "form-control" })
            @Html.ValidationMessageFor(e => e.WorkoutExercise.AdditionalName)
        </div>
        <div class="form-group">
            @Html.LabelFor(e => e.WorkoutExercise.Wraps)
            @Html.TextBoxFor(e => e.WorkoutExercise.Wraps, new { @class = "form-control" })
            @Html.ValidationMessageFor(e => e.WorkoutExercise.Wraps)
        </div>
        <div class="form-group">
            @Html.LabelFor(e => e.WorkoutExercise.WorkingWeight)
            @Html.TextBoxFor(e => e.WorkoutExercise.WorkingWeight, new { @class = "form-control" })
            @Html.ValidationMessageFor(e => e.WorkoutExercise.WorkingWeight)
        </div>
        <div class="form-group">
            @Html.LabelFor(e => e.WorkoutExercise.NumberOfSets)
            @Html.TextBoxFor(e => e.WorkoutExercise.NumberOfSets, new { @class = "form-control" })
            @Html.ValidationMessageFor(e => e.WorkoutExercise.NumberOfSets)
        </div>

        @Html.HiddenFor(e => e.WorkoutExercise.WorkoutId, new { Value = Model.WorkoutId })
        @Html.HiddenFor(e => e.WorkoutExercise.Id)
        @Html.AntiForgeryToken()
        <button type="submit" class="btn btn-primary">@Model.ButtonText</button>

    }

</div>
@section scripts
        {

@Scripts.Render("~/bundles/jqueryval")
    <script>
        $(document).ready(function () {
            $('#deletebutton > form').submit(function (e) {
                e.preventDefault();
                bootbox.confirm("Вы уверены, что хотите удалить?", function (result) {
                    if (result) {
                        $('#deletebutton > form').unbind('submit').submit();
                    }
                })
            });
        });
    </script>

}